runtime: python312
# env: flex
service: stdpy3
entrypoint: gunicorn --bind 0.0.0.0:8080 main:app

# manual_scaling:
#   instances: 1
instance_class: F2
vpc_access_connector:
  name: "projects/<redacted>/locations/asia-south1/connectors/gaevpc"
  egress_setting: all-traffic